version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
  consumer:
    build:
      context: ./consumer
    environment:
      NODE_ENV: production
      MONGO: 
    deploy:
      replicas: 5
    networks: 
      - rabbitmq_go_net
  producer:
    build:
      context: ./producer
    environment:
      NODE_ENV: production
      MONGO: 
      FILES: 10
    networks:
      - rabbitmq_go_net
    deploy:
      replicas: 2

networks:
  rabbitmq_go_net:
    driver: bridge
